### ISSUE TITLE
[PE-D] Category is shown as required field in update product window

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-4/tp#199] opened 2022-04-01 17:38 UTC
On the add product window, category is shown as an optional field. However, on the update product window, it is shown to be required but having it as empty will work

![image.png](https://raw.githubusercontent.com/louisdavinlie/ped/main/files/8b8f939e-74d3-41ce-827f-ee7e0a2738f6.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: louisdavinlie/ped#4

**Comment by MechFroG88** [comment] 2022-04-01 19:31
Duplicate of #192

**Closed by MechFroG88** 2022-04-01 19:31 UTC
