### ISSUE TITLE
Error messages not showing

### ISSUE THREAD

**Issue by mazx4960** [AY2122S2-CS2103T-T09-4/tp#140] opened 2022-03-31 01:27 UTC
**Describe the bug**

- When a button like add item is clicked, the error message would not be shown

**To Reproduce**

- click add item button then run any command

**Expected behavior**

- error messages should be shown

**Comment by MechFroG88** [comment] 2022-03-31 08:48
Duplicate of #148, Fixed in #149

**Closed** 2022-03-31 17:53 UTC
Labels: type.Bug
